name: shadowsocks-libev.v2ray-plugin

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'version'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        id: prepare
        run: |
          VERSION=${{ github.event.input.version }}
          VERSION=${VERSION:1.3.1}
          IMAGE_NAME=shadowsocks-libev
          TAGS="gists/${IMAGE_NAME}:v2ray-plugin-${VERSION},gists/${IMAGE_NAME}:v2ray-plugin-latest"
          echo ::set-output name=build_args::VERSION=${VERSION}
          echo ::set-output name=image-name::${IMAGE_NAME}
          echo ::set-output name=tags::${TAGS}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./shadowsocks/libev+v2ray
          file: ./shadowsocks/libev+v2ray/Dockerfile
          platforms: linux/386,linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7,linux/ppc64le,linux/s390x
          push: ${{ github.event_name != 'pull_request' }}
          build-args: ${{ steps.prepare.outputs.build_args }}
          tags: ${{ steps.prepare.outputs.tags }}
      - name: Clear
        if: always()
        run: |
          rm -rf ${HOME}/.docker/config.json
